services:
  devops:
    image: 5pmgrass/tenviac
    volumes:
      # Store the history
      - devops_history:/root/bash_history
      # Volume in the repo rather than copying it (saves time on start)
      - ./:/root/repo
      # Just in case we have any ssh to deal with
      - $HOME/.ssh:/root/.ssh
      # enable aws access
      - ~/.aws:/root/.aws
      - tenv:/root/.tenv

volumes:
  devops_history:
  tenv: