hello: ENC[AES256_GCM,data:vor5GjbYdPslpeg0CyG1fPOKX8CpOgr3arVec0auQ8iGTvGljW5GYjEMK9JqEdP1pKefDKJTPGRvnbbE8Eo=,iv:zB61/KDAWH8Jdgiz2Ws61vdOBLSuRHTEDwl6zWiZlUg=,tag:fTef4FugKWEq+AZZsek2LQ==,type:str]
example_key: ENC[AES256_GCM,data:WCocqhlrWJGdMTVWbg==,iv:8+aqovx2CQwPSpTlbkOfviimgQyzPIGu3U5eTyZuw54=,tag:z3nR8p3zjCAXy+FAZlmdAw==,type:str]
#ENC[AES256_GCM,data:2MY6Ad20hNFf3q1U8veedw==,iv:jIbb3ceHnqRdpnN/eY3uYb2XnOAg59XGVVbWMNmqcYE=,tag:UhE37hadECa2hYV5Z0PaKQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:kP0L863uuMCVTEIrAA4=,iv:o5RzauAD4gesIepiLEgbiTp3G5Oyslseoyf50SX6/3U=,tag:/TUOiE1Y7qFV94wZs7ltHQ==,type:str]
    - ENC[AES256_GCM,data:NmLTQx0DYKPFtfkbmVs=,iv:7I1VJV+1TeV3Aw1wtLY0QwPEXVyy09WWoky94Y8A2uY=,tag:fL5uQYHRPZQ7fJp8i/dqFw==,type:str]
example_number: ENC[AES256_GCM,data:ATtO4IrQG6EFHg==,iv:vU/FW9WtBFXn9bLNJ/lGGQde5RCc2xU4z9tIUvNPXNI=,tag:9Mj+5wGl9QirTfEjXxsk0w==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:+jILnQ==,iv:siio6utwzc7124G6NKkhHabAbXq66CgHt/2Amya0VFg=,tag:st1xt1XN0bMqTE0hqftqWQ==,type:bool]
    - ENC[AES256_GCM,data:zgR86KA=,iv:oAy2QJonrk/JtrOJrhchb6exbrV+qDTT7rfvou1mHFQ=,tag:Krs8H2BBVnGGTWbe2ZqNIA==,type:bool]
hosted_zone: ENC[AES256_GCM,data:kCIVgexvZuKba92AEQKL4ADaFec=,iv:w/aIdMlMeysQCqxtyUxnHx64xg/QRqlxzrGWKJHL3qI=,tag:FVrK63+5MhfYuVIHSI7l/g==,type:str]
domain: ENC[AES256_GCM,data:F1RmNKecl7SvgUn91glEccHDsTZzDw==,iv:vT4ORSJcK2PRHVRaIW+d6/4rN7pA6NMvLgKBO2WOmrM=,tag:G8etFbUeMJYssDGqzBdbxw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:637271283041:key/07be2be9-15d7-44b9-a885-b48952f478ad
          created_at: "2023-03-15T02:33:28Z"
          enc: AQICAHjj6aP3l6DVQcyVHokJYu3VYk+d29HvcNKDxWVZ1FLmHgFsEuiTAkfwMeKEJO6lFv3mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYfdAhCgg9lBIAylfAgEQgDvGPISAf8ElBHZQEj9asuFqS3PIZdpKB4qSmd0x8dwgt6qQPLfPPEFDlqwbF2b7als+U1BC15OiC3y/fw==
          aws_profile: ""
    lastmodified: "2025-11-29T02:53:59Z"
    mac: ENC[AES256_GCM,data:B3cmSS/nR1YTGO2loZ8zJJncEOvjymdr/yB6bJA7AzSoRBKOQNPcsdhm3GYgG2UBwQBT4Y9Tb7p2aTCBTZaISqmtW+u64CGUz++l5+l5rDr2eDBolakYi+AJwoNZvA8buEnEDYgA9ZfTX9HaaN7fEpBDzc/HhdF4wrHjQhmV3z4=,iv:T5pYxxflIF6Xic5ESpW1j8rUNQ6Jpk0oZQ5BOqrZK4g=,tag:Cp9I5wHdLTXLPm0/rnPsXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
